### ISSUE TITLE
What terminal emulator or setting is needed to run Pash?

### ISSUE THREAD

**Issue by GergelyBuday** [Pash-Project/Pash#293]
I ran Pash and got 

$ mono Source/PashConsole/bin/Debug/Pash.exe
[%?%p1%{8}%<%t37%e%p1%{16}%<%t9%p1%{8}%-%d%e38;5;7%;m[%?%p1%{8}%<%t40%e%p1%{16}%<%t10%p1%{8}%-%d%e48;5;0%;mPash - Copyright (C) Pash Contributors.     License: GPL/BSD. See https://github.com/Pash-Project/Pash/
[%?%p1%{8}%<%t37%e%p1%{16}%<%t9%p1%{8}%-%d%e38;5;7%;m[%?%p1%{8}%<%t40%e%p1%{16}%<%t10%p1%{8}%-%d%e48;5;0%;m
[%?%p1%{8}%<%t37%e%p1%{16}%<%t9%p1%{8}%-%d%e38;5;7%;m[%?%p1%{8}%<%t40%e%p1%{16}%<%t10%p1%{8}%-%d%e48;5;0%;mPASH /home/gbuday/projects/Pash> [%?%p1%{8}%<%t37%e%p1%{16}%<%t9%p1%{8}%-%d%e38;5;7%;m[%?%p1%{8}%<%t40%e%p1%{16}%<%t10%p1%{8}%-%d%e48;5;0%;m 

I was told that I have to make my gnome terminal understand ansi sequences. How can I do that? Or, I need some other terminal emulator software? Is this written somewhere in the documentation?

**Comment by staxmanade** [comment]
FYI: this site now has a [F.A.Q.](http://pash-project.github.io/faq/). @ALL - please feel free to extend this list, or submit an issue over on the website rewp.
