### ISSUE TITLE
Broken Powershell API compatibility in provider implementation

### ISSUE THREAD

**Issue by sburnicki** [Pash-Project/Pash#339]
Working on the providers I noticed that currently Pash's implementation of `ItemCmdletProvider`, `SessionStateProviderBase`, and others differ from the official Powershell API, because their methods all take `Path` objects instead of regular `string`s.

git log and blame are telling me that @staxmanade did this in March 2013 with the message:
`replace many many usages of 'string path' with 'Path path' in prep for a cleanup on path usages`

However, I would really like to revert this during my work, so we are staying compatible to Powershell. After all, this would prevent us from writing providers that work with both Pash and Powershell. And I really want to write such a provider, and I also think that it's a major feature as a cross-platform shell.

Any thoughts on this? I just didn't want to revert it without asking the original author ;)

**Comment by staxmanade** [comment]
Make whatever changes you need... I thought (at the time) it was a good approach, but am afraid it may not have been and am not surprised to see it come up - so sorry about that.

**Comment by sburnicki** [comment]
No problem :) I just wanted to make sure I'm not missing something important here. The general approach makes sense, it's just unfortunately breaking the compatibility :/
