### ISSUE TITLE
Weird corner case in unit tests (Wine & Win platform specific tests)

### ISSUE THREAD

**Issue by castarco** [Pash-Project/Pash#342]
Hello,

I've been trying to run the Pash unit tests on Wine, and I've found many not well covered corner cases in the unit tests, specifically in the TestHost subpackage.

For example, in the "TestHost/7.1.2 - Member Access.cs" file, lines 226-233, the test CallGetTypeMethodOnSystemEnvironmentOnWindows fails when runs on Wine because Wine uses Mono instead of Microsoft .NET, and exposes "System.MonoType" instead of "System.RuntimeType".

It seems that this is not a Pash bug nor a Wine bug, but a weird corner case.

What should be done with this cases?

P.D.: I think that maybe it's better to check the runtime version ( https://stackoverflow.com/questions/721161/how-to-detect-which-net-runtime-is-being-used-ms-vs-mono ) and then test the appropriate command than creating a platform-specific test.

**Comment by mrward** [comment]
Agreed some of those tests are Mono specific rather than platform specific. It would be nice if we could do something like:

     [Platform("mono")]

Although it might be simpler to just merge the two tests together and use a helper method or class to return the type string we are using in the assert:

    "System.MonoType"
    "System.RuntimeType"

**Comment by sburnicki** [comment]
Why not replace these platform dependent tests with a single one that tests against something like `typeof(System.Environment).GetTyp().FullName`? This would be platform independent and assures that the semantics of the piece of code corresponds to what it should express.

**Comment by castarco** [comment]
@mrward @sburnicki I've sent a pull request : https://github.com/Pash-Project/Pash/pull/343

**Comment by sburnicki** [comment]
Great. Did this solve all issues for you?

**Comment by castarco** [comment]
@sburnicki Yes :) , sorry for not closing the issue. I forgot to do it.
