### ISSUE TITLE
Select-String sets wrong LineNumber

### ISSUE THREAD

**Issue by sburnicki** [Pash-Project/Pash#376]
```
"foobar" | Out-File tmp1.txt
"barbaz" | Out-File tmp2.txt
Select-String bar* *.txt
```
results in `MatchInfo` objects with strange line numbers. Both output objects should obviously have `LineNumber` set to `1`, but in my example they are set to `8` and `9`.

**Comment by mrward** [comment]
Looks like the line number is not being reset for each file so it keeps incrementing. I will add a test and fix this.
