### ISSUE TITLE
$Host unusable?

### ISSUE THREAD

**Issue by Phrohdoh** [Pash-Project/Pash#395]
After a bit of investigation on #394 I discovered that `$Host` causes an argument to be null, but these error messages are far from helpful, unfortunately.
I don't know the policy on stacktrace verbosity.

From this I assume `$Host` is not implemented.

**Comment by mrward** [comment]
The $host variable is now available.

394c0fde76112e99fea590ab0bf579e403c9c0f7

**Comment by Phrohdoh** [comment]
Awesome, thanks. :-)
