### ISSUE TITLE
finally clause quircks

### ISSUE THREAD

**Issue by ForNeVeR** [Pash-Project/Pash#411]
As reported at [our maillist](https://groups.google.com/forum/#!topic/pash-project/5KfPeeLza8g), we have some problems with `finally` clause.

1. I got an exception with the following example:

   ```
Pash> try { 2 + 2 } finally { 0 }
System.InvalidOperationException: expected 'finally_clause' to be a 'catch_clauses'
   в Pash.ParserIntrinsics.AstBuilder.VerifyTerm(ParseTreeNode parseTreeNode, BnfTerm expectedTerm, BnfTerm[] moreExpectedTerms) в D:\X-Files\Projects\Pash\Source\System.Management\Pash\ParserIntrinsics\AstBuilder.cs:строка 40
   в Pash.ParserIntrinsics.AstBuilder.BuildCatchClausesAst(ParseTreeNode parseTreeNode) в D:\X-Files\Projects\Pash\Source\System.Management\Pash\ParserIntrinsics\AstBuilder.cs:строка 437
   в Pash.ParserIntrinsics.AstBuilder.BuildTryStatementAst(ParseTreeNode parseTreeNode) в D:\X-Files\Projects\Pash\Source\System.Management\Pash\ParserIntrinsics\AstBuilder.cs:строка 427
   ```
2. That exception has killed the Pash process although generally parser exceptions shouldn't do that. (I am not sure how it does that; maybe that's a separate issue. Please provide more details while researching that.)
3. We also have an inconsistency with PowerShell when returning the values from the `finally` clause. For example, the following will return a list with two values in PowerShell:

   ```
PS> $x = try { 2 + 2 } catch { } finally { 0 }
PS> $x
4
0
   ```

   But in Pash it returns only 4 and not 0. We should check the spec again and ultimately fix that inconsistency.

**Comment by sburnicki** [comment]
Finally terms aren't considered when building the parse tree in AstBuilder.cs:425.
And this is also why Pash is crashing: Parsing technically works, but there is a real *bug* when building the parse tree as it assumes that all terms following the `try` are `catch` clauses which is obviously wrong.

Currently Pash can only recover from problems in parsing and execution. Building the parse tree is an intermediate step where Pash doesn't provide error recovery, yet.

I will resolve this bug and add support for finally clauses :)
