### ISSUE TITLE
Case sensitivity not present on linux

### ISSUE THREAD

**Issue by SRGOM** [Pash-Project/Pash#418]
I have the following dir structure

    . .. Downloads

However, when I do

    (dir|where {$_.Name -eq "Downloads"}).Exists 
    (dir|where {$_.Name -eq "downloads"}).Exists 

Both return `True`. The second should return false. I'm on the latest github code:

`Linux XYZ 3.13.0-37-generic #64-Ubuntu SMP Mon Sep 22 21:30:01 UTC 2014 i686 i686 i686 GNU/Linux`

**Comment by ygra** [comment]
>> (dir|where {$_.Name -eq "Downloads"}).Exists
 >> (dir|where {$_.Name -eq "downloads"}).Exists

Note that -eq is case-*in*sensitive. The case-sensitive operator is 
-ceq. So I'd say what you're experiencing is expected and correct.

Regards,
Johannes
