### ISSUE TITLE
AppVeyor build problems

### ISSUE THREAD

**Issue by ForNeVeR** [Pash-Project/Pash#421]
Currently our build is broken, see https://ci.appveyor.com/project/JayBazuzi/pash/build/0.0.216

Need to fix that.

**Comment by ForNeVeR** [comment]
It's already night at my location, but I'll try to take care of it tomorrow if nobody else wants to do it before.

**Comment by ygra** [comment]
Apparently the build machine has a newer version of the PowerShell assemblies which require .NET 4.5. Maybe we could either try to force AppVeyor to use an older OS on the build machine, or build against the current assemblies by increasing our TargetFramework. I'm not sure whether we actually _want_ to do the latter, though.

**Comment by JayBazuzi** [comment]
I thought maybe we could ask AppVeyor to run on a downstream OS, but apparently [they only support WS2012R2](https://www.appveyor.com/docs/installed-software#operating-system). So we'll have to deal with that.

My hesitation around .NET 4.5 is compatibility with other systems. 

How is Mono's 4.5 support? 

How 'bout Travis? They officially support recent versions of Mono, according to https://docs.travis-ci.com/user/languages/csharp/#Choosing-Mono-version-to-test-against.

We should give it a try and see if things work.

**Comment by ForNeVeR** [comment]
http://www.mono-project.com/docs/about-mono/compatibility/

It seems that .NET 4.5 have good support on Mono 4.0+. I can remember some problems regarding generic `Array.Empty<T>`, but that's all.

I've been  testing .NET 4.5 project on Travis, here's a [`.travis.yml` example](https://github.com/codingteam/naggum/blob/develop/.travis.yml). `mono: latest` does the right thing.

**Comment by JayBazuzi** [comment]
Moved to .NET v4.5 with PR #424
